### ISSUE TITLE
Trouble building  (ffmpeg 3.4.1)

### ISSUE THREAD

**Issue by BorisMolch** [protyposis/AudioAlign#5] opened 2018-01-10 21:17 UTC
Could not build with latest ffmpeg version. 
downloaded 3.3.3 and build looks good so far

**Comment by protyposis** [comment] 2018-01-16 17:27
Closing as duplicate of https://github.com/protyposis/Aurio/issues/6.

**Closed as completed by protyposis** 2018-01-16 17:27 UTC
